// "use client";
import Navbar from "@/component/navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import QueryProvider from "@/queryProvider/queryProvider";
import { Provider } from "react-redux";
import { store } from "../RTK/store";

const inter = Poppins({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <QueryProvider>
        <Provider store={store}>
          <body className={inter.className}>
            <Navbar />
            {children}
          </body>
        </Provider>
      </QueryProvider>
    </html>
  );
}
